version: '3.8'
services:
  spring-boot-app:
    build: .
    container_name: spring-boot
    restart: always
    ports:
      - "8090:8080"
    depends_on:
      - mariadb
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/bridge
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=bridge
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      - MARIADB_DATABASE=bridge
      - MARIADB_ROOT_PASSWORD=bridge
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=bridge
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  redis:
    image: redis
    container_name: redis
    hostname: bridge_redis
    restart: always
    ports:
      - "6380:6379"
volumes:
  mariadb_data: