spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-container:3306/bridge
    username: root
    password: bridge

  #JPA
  jpa:
    show_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
    #Server Port
    server:
      port: 8080

  #mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: #google계정
    password: #발급받은 앱 비밀번호
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          starttls:
            enable: true
          auth: true
  #Redis
  #data:
    #redis:
      #host: bridge_redis
      #port: 6379


