spring:
  config:
    activate:
      on-profile: test
  datasource:
    datasource:
      url: jdbc:h2:mem:bridge
      username: sa
      password:
      driver-class-name: org.h2.Driver
  #JPA
  jpa:
    show_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  #Redis
  data:
    redis:
      # host: bridge_redis1
      host: localhost
      port: 6379

#Server Port
server:
  port: 8081

#mail
mail:
  host: smtp.gmail.com
  port: 587
  username: #google계정
  password: #발급받은 앱 비밀번호
  properties:
    mail:
      smtp:
        connectiontimeout: 5000
        starttls:
          enable: true
        auth: true
logging:
  level:
    org:
      hibernate:
        sql: debug
